name: open_meteo
description: A simple, fast, asynchronous Dart/Flutter client package for OpenMeteo API.
version: 0.1.1
homepage: https://github.com/Neurs12/open-meteo-dart

environment:
  sdk: '>=2.19.0 <4.0.0'


dependencies:
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1