name: open_meteo
description: A simple, fast, asynchronous Dart/Flutter SDK package for Open-Meteo API.
version: 1.0.8
homepage: https://github.com/Neurs12/open-meteo-dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flat_buffers: ^23.5.26
  freezed_annotation: ^2.4.2
  http: ^1.2.1
dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.4
  lints: ^4.0.0
  test: ^1.25.8
